CREATE TABLE payslip (
    id                    UUID            NOT NULL,
    company_id            UUID            NOT NULL,
    employee_id           UUID            NOT NULL,
    payroll_period_id     UUID            NOT NULL,
    estado                VARCHAR(20)     NOT NULL,
    tipo                  VARCHAR(20)     NOT NULL DEFAULT 'NORMAL',
    payslip_original_id   UUID,
    sueldo_base           NUMERIC(14, 2)  NOT NULL,
    horas_normales        NUMERIC(10, 2)  NOT NULL DEFAULT 0,
    horas_extra           NUMERIC(10, 2)  NOT NULL DEFAULT 0,
    horas_feriado         NUMERIC(10, 2)  NOT NULL DEFAULT 0,
    bruto_calculado       NUMERIC(14, 2)  NOT NULL,
    total_deducciones     NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    total_adelantos       NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    neto_final            NUMERIC(14, 2)  NOT NULL,
    detalle_descuentos    TEXT            NOT NULL DEFAULT '[]',
    adelantos_aplicados   TEXT            NOT NULL DEFAULT '[]',
    fecha_pago            DATE,
    motivo_anulacion      VARCHAR(1000),
    CONSTRAINT pk_payslip                 PRIMARY KEY (id),
    CONSTRAINT fk_payslip_company         FOREIGN KEY (company_id)        REFERENCES company (id),
    CONSTRAINT fk_payslip_employee        FOREIGN KEY (employee_id)        REFERENCES employee (id),
    CONSTRAINT fk_payslip_payroll_period  FOREIGN KEY (payroll_period_id)  REFERENCES payroll_period (id)
);
